services:
  server:
    deploy:
      replicas: 4
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 10s
        order: start-first
      rollback_config:
        parallelism: 1
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik_net'
      # Common
      - 'traefik.http.services.api-srv.loadbalancer.server.port=3000'
      # HTTP Routers
      - 'traefik.http.routers.api-srv.rule=Host(`api.ragna.io`)'
      - 'traefik.http.routers.api-srv.entrypoints=https'
      - 'traefik.http.routers.api-srv.service=api-srv'
      - 'traefik.http.routers.api-srv.middlewares=crowdsec-bouncer@file,default@file' #,gzip@file
      - 'traefik.http.routers.api-srv.tls=true'
      - 'traefik.http.routers.api-srv.tls.certresolver=http'
    networks:
      traefik_net:

  postgres:
    networks:
      - wgnet

networks:
  traefik_net:
    external: true
  wgnet:
    external: true
