# docker-compose.yml
name: ragna-backend

volumes:
  postgres_data:
  redis_data:

services:
  app:
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  postgres:
    cpus: 4
    image: postgres:17.0-alpine3.20
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    security_opt:
      - no-new-privileges:true
    networks:
      - app-network

  redis:
    image: redis:7.4-alpine
    command: 'redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}'
    volumes:
      - redis_data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
